test "absolute(8.)" (fun () -> expect (Float.absolute 8.) |> toEqual Eq.float 8.) ; 
test "absolute(-7.)" (fun () -> expect (Float.absolute -7.) |> toEqual Eq.float 7.) ; 
test "absolute(0.)" (fun () -> expect (Float.absolute 0.) |> toEqual Eq.float 0.) ; 
test "add(3.14,3.14)" (fun () -> expect (Float.add 3.14 3.14) |> toEqual Eq.float 6.28) ; 
test "atan(0.)" (fun () -> expect (Float.atan 0.) |> toEqual Eq.radians 0.) ; 
test "atan(1. /. 1.)" (fun () -> expect (Float.atan 1. /. 1.) |> toEqual Eq.radians 0.7853981633974483) ; 
test "atan(1. /. -1.)" (fun () -> expect (Float.atan 1. /. -1.) |> toEqual Eq.radians -0.7853981633974483) ; 
test "atan(-1. /. -1.)" (fun () -> expect (Float.atan -1. /. -1.) |> toEqual Eq.radians 0.7853981633974483) ; 
test "atan(-1. /. 1.)" (fun () -> expect (Float.atan -1. /. 1.) |> toEqual Eq.radians -0.7853981633974483) ; 
test "ceiling(1.2)" (fun () -> expect (Float.ceiling 1.2) |> toEqual Eq.float 2.) ; 
test "ceiling(1.5)" (fun () -> expect (Float.ceiling 1.5) |> toEqual Eq.float 2.) ; 
test "ceiling(1.8)" (fun () -> expect (Float.ceiling 1.8) |> toEqual Eq.float 2.) ; 
test "ceiling(-1.2)" (fun () -> expect (Float.ceiling -1.2) |> toEqual Eq.float -1.) ; 
test "ceiling(-1.5)" (fun () -> expect (Float.ceiling -1.5) |> toEqual Eq.float -1.) ; 
test "ceiling(-1.8)" (fun () -> expect (Float.ceiling -1.8) |> toEqual Eq.float -1.) ; 
test "cos(degrees(60.))" (fun () -> expect (Float.cos degrees(60.)) |> toEqual Eq.float 0.5) ; 
test "cos(radians(pi /. 3.))" (fun () -> expect (Float.cos radians(pi /. 3.)) |> toEqual Eq.float 0.5) ; 
test "degrees(180.)" (fun () -> expect (Float.degrees 180.) |> toEqual Eq.radians pi) ; 
test "floor(1.2)" (fun () -> expect (Float.floor 1.2) |> toEqual Eq.float 1.) ; 
test "floor(1.5)" (fun () -> expect (Float.floor 1.5) |> toEqual Eq.float 1.) ; 
test "floor(1.8)" (fun () -> expect (Float.floor 1.8) |> toEqual Eq.float 1.) ; 
test "floor(-1.2)" (fun () -> expect (Float.floor -1.2) |> toEqual Eq.float -2.) ; 
test "floor(-1.5)" (fun () -> expect (Float.floor -1.5) |> toEqual Eq.float -2.) ; 
test "floor(-1.8)" (fun () -> expect (Float.floor -1.8) |> toEqual Eq.float -2.) ; 
test "fromInt(5)" (fun () -> expect (Float.fromInt 5) |> toEqual Eq.float 5.0) ; 
test "fromInt(0)" (fun () -> expect (Float.fromInt 0) |> toEqual Eq.float 0.0) ; 
test "fromInt(-7)" (fun () -> expect (Float.fromInt -7) |> toEqual Eq.float -7.0) ; 
test "fromString("NaN")" (fun () -> expect (Float.fromString "NaN") |> toEqual (let open Eq in option float) Some(Js.Float._NaN),) ; 
test "fromString("nan")" (fun () -> expect (Float.fromString "nan") |> toEqual (let open Eq in option float) Some(Js.Float._NaN)) ; 
test "fromString("Infinity")" (fun () -> expect (Float.fromString "Infinity") |> toEqual (let open Eq in option float) Some(infinity)) ; 
test "fromString("infinity")" (fun () -> expect (Float.fromString "infinity") |> toEqual (let open Eq in option float) None) ; 
test "fromString("55")" (fun () -> expect (Float.fromString "55") |> toEqual (let open Eq in option float) Some(55.)) ; 
test "fromString("-100")" (fun () -> expect (Float.fromString "-100") |> toEqual (let open Eq in option float) Some(-100.)) ; 
test "fromString("not number")" (fun () -> expect (Float.fromString "not number") |> toEqual (let open Eq in option float) None) ; 
test "isFinite(infinity)" (fun () -> expect (Float.isFinite infinity) |> toEqual Eq.bool false) ; 
test "isFinite(negativeInfinity)" (fun () -> expect (Float.isFinite negativeInfinity) |> toEqual Eq.bool false) ; 
test "isFinite(nan)" (fun () -> expect (Float.isFinite nan) |> toEqual Eq.bool false) ; 
test "isFinite(-5.)" (fun () -> expect (Float.isFinite -5.) |> toEqual Eq.bool true) ; 
test "isFinite(-0.314)" (fun () -> expect (Float.isFinite -0.314) |> toEqual Eq.bool true) ; 
test "isFinite(0.)" (fun () -> expect (Float.isFinite 0.) |> toEqual Eq.bool true) ; 
test "isFinite(3.14)" (fun () -> expect (Float.isFinite 3.14) |> toEqual Eq.bool true) ; 
test "isInfinite(infinity)" (fun () -> expect (Float.isInfinite infinity) |> toEqual Eq.bool true) ; 
test "isInfinite(negativeInfinity)" (fun () -> expect (Float.isInfinite negativeInfinity) |> toEqual Eq.bool true) ; 
test "isInfinite(nan)" (fun () -> expect (Float.isInfinite nan) |> toEqual Eq.bool false) ; 
test "isInfinite(-5.)" (fun () -> expect (Float.isInfinite -5.) |> toEqual Eq.bool false) ; 
test "isInfinite(-0.314)" (fun () -> expect (Float.isInfinite -0.314) |> toEqual Eq.bool false) ; 
test "isInfinite(0.)" (fun () -> expect (Float.isInfinite 0.) |> toEqual Eq.bool false) ; 
test "isInfinite(3.14)" (fun () -> expect (Float.isInfinite 3.14) |> toEqual Eq.bool false) ; 
test "isInteger(5.0)" (fun () -> expect (Float.isInteger 5.0) |> toEqual Eq.bool true) ; 
test "isInteger(pi)" (fun () -> expect (Float.isInteger pi) |> toEqual Eq.bool false) ; 
test "isNaN(nan)" (fun () -> expect (Float.isNaN nan) |> toEqual Eq.bool true) ; 
test "isNaN(91.4)" (fun () -> expect (Float.isNaN 91.4) |> toEqual Eq.bool false) ; 
test "negate(8.)" (fun () -> expect (Float.negate 8.) |> toEqual Eq.float -8.) ; 
test "negate(-7.)" (fun () -> expect (Float.negate -7.) |> toEqual Eq.float 7.) ; 
test "negate(0.)" (fun () -> expect (Float.negate 0.) |> toEqual Eq.float -0.) ; 
test "radians(pi)" (fun () -> expect (Float.radians pi) |> toEqual Eq.radians pi) ; 
test "sin(degrees(30.))" (fun () -> expect (Float.sin degrees(30.)) |> toEqual Eq.float 0.5) ; 
test "sin(radians(pi /. 6.))" (fun () -> expect (Float.sin radians(pi /. 6.)) |> toEqual Eq.float 0.5) ; 
test "squareRoot(4.)" (fun () -> expect (Float.squareRoot 4.) |> toEqual Eq.float 2.) ; 
test "squareRoot(20.25)" (fun () -> expect (Float.squareRoot 20.25) |> toEqual Eq.float 4.5) ; 
test "squareRoot(-1.)" (fun () -> expect (Float.squareRoot -1.) |> toEqual Eq.float NaN) ; 
test "tan(degrees(45.))" (fun () -> expect (Float.tan degrees(45.)) |> toEqual Eq.float 0.9999999999999999) ; 
test "tan(radians(pi /. 4.))" (fun () -> expect (Float.tan radians(pi /. 4.)) |> toEqual Eq.float 0.9999999999999999) ; 
test "tan(0.)" (fun () -> expect (Float.tan 0.) |> toEqual Eq.float 0.) ; 
test "toInt(5.)" (fun () -> expect (Float.toInt 5.) |> toEqual (let open Eq in option int) Some(5)) ; 
test "toInt(5.3)" (fun () -> expect (Float.toInt 5.3) |> toEqual (let open Eq in option int) Some(5)) ; 
test "toInt(0.)" (fun () -> expect (Float.toInt 0.) |> toEqual (let open Eq in option int) Some(0)) ; 
test "toInt(-7.)" (fun () -> expect (Float.toInt -7.) |> toEqual (let open Eq in option int) Some(-7)) ; 
test "toInt(nan)" (fun () -> expect (Float.toInt nan) |> toEqual (let open Eq in option int) None) ; 
test "toInt(infinity)" (fun () -> expect (Float.toInt infinity) |> toEqual (let open Eq in option int) None) ; 
test "toInt(negativeInfinity)" (fun () -> expect (Float.toInt negativeInfinity) |> toEqual (let open Eq in option int) None) ; 
test "truncate(1.2)" (fun () -> expect (Float.truncate 1.2) |> toEqual Eq.float 1.) ; 
test "truncate(1.5)" (fun () -> expect (Float.truncate 1.5) |> toEqual Eq.float 1.) ; 
test "truncate(1.8)" (fun () -> expect (Float.truncate 1.8) |> toEqual Eq.float 1.) ; 
test "truncate(-1.2)" (fun () -> expect (Float.truncate -1.2) |> toEqual Eq.float -1.) ; 
test "truncate(-1.5)" (fun () -> expect (Float.truncate -1.5) |> toEqual Eq.float -1.) ; 
test "truncate(-1.8)" (fun () -> expect (Float.truncate -1.8) |> toEqual Eq.float -1.) ; 
test "turns(1.)" (fun () -> expect (Float.turns 1.) |> toEqual Eq.radians 2. *. pi) ; 
