// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Tablecloth = require("tablecloth-bucklescript/src/tablecloth.bs.js");

if (Tablecloth.$$String[/* length */0] === Tablecloth.$$String[/* length */0]) {
  console.log("Strings match");
} else {
  console.log("strings dont match");
}

/*  Not a pure module */
