let () = {
  Alcotest.run(
    "Tablecloth",
    [
      (
        "tests",
        [
          ArrayTest.suite,
          BoolTest.suite,
          CharTest.suite,
          FloatTest.suite,
          FunTest.suite,
          IntTest.suite,
          ListTest.suite,
          MapTest.suite,
          OptionTest.suite,
          ResultTest.suite,
          SetTest.suite,
          StringTest.suite,
          Tuple2Test.suite,
          Tuple3Test.suite,
        ],
      ),
    ],
  );
};
