test ("isLetter('A')", () => expect(Char.isLetter('A')) |> toEqual(Eq.bool, true)) 
test ("isLetter('7')", () => expect(Char.isLetter('7')) |> toEqual(Eq.bool, false)) 
test ("isLetter(' ')", () => expect(Char.isLetter(' ')) |> toEqual(Eq.bool, false)) 
test ("isLetter('\n')", () => expect(Char.isLetter('\n')) |> toEqual(Eq.bool, false)) 
test ("isLetter('\001')", () => expect(Char.isLetter('\001')) |> toEqual(Eq.bool, false)) 
test ("isLetter('\236')", () => expect(Char.isLetter('\236')) |> toEqual(Eq.bool, false)) 
